use chrono::{DateTime, Duration, Utc};
use serde::{Deserialize, Serialize};
use strum::{EnumIter, FromRepr};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, EnumIter, FromRepr, Serialize, Deserialize)]
#[non_exhaustive]
#[repr(u8)]
pub enum RollingWindow {
    Seconds5,
    Seconds10,
    Seconds15,
    Seconds30,
    Seconds60,
    Minutes1,
    Minutes2,
    Minutes3,
    Minutes5,
    Minutes10,
    Minutes15,
    Minutes30,
    Minutes45,
    Minutes60,
    Minutes90,
    Hours1,
    Hours2,
    Hours3,
    Hours4,
    Hours6,
    Hours8,
    Hours12,
    Hours24,
    Days1,
    Days2,
    Days3,
    Days7,
    Days14,
    Days30,
    Days45,
    Days60,
    Days90,
    Days180,
    Days360,
    Weeks1,
    Weeks2,
    Weeks4,
    Weeks10,
    Weeks20,
    Weeks40,
}

impl RollingWindow {
    pub fn checked_add(&self, date_time: DateTime<Utc>) -> Option<DateTime<Utc>> {
        match self {
            RollingWindow::Seconds5 => Some(date_time + Duration::seconds(5)),
            RollingWindow::Seconds10 => Some(date_time + Duration::seconds(10)),
            RollingWindow::Seconds15 => Some(date_time + Duration::seconds(15)),
            RollingWindow::Seconds30 => Some(date_time + Duration::seconds(30)),
            RollingWindow::Seconds60 => Some(date_time + Duration::seconds(60)),
            RollingWindow::Minutes1 => Some(date_time + Duration::minutes(1)),
            RollingWindow::Minutes2 => Some(date_time + Duration::minutes(2)),
            RollingWindow::Minutes3 => Some(date_time + Duration::minutes(3)),
            RollingWindow::Minutes5 => Some(date_time + Duration::minutes(5)),
            RollingWindow::Minutes10 => Some(date_time + Duration::minutes(10)),
            RollingWindow::Minutes15 => Some(date_time + Duration::minutes(15)),
            RollingWindow::Minutes30 => Some(date_time + Duration::minutes(30)),
            RollingWindow::Minutes45 => Some(date_time + Duration::minutes(45)),
            RollingWindow::Minutes60 => Some(date_time + Duration::minutes(60)),
            RollingWindow::Minutes90 => Some(date_time + Duration::minutes(90)),
            RollingWindow::Hours1 => Some(date_time + Duration::hours(1)),
            RollingWindow::Hours2 => Some(date_time + Duration::hours(2)),
            RollingWindow::Hours3 => Some(date_time + Duration::hours(3)),
            RollingWindow::Hours4 => Some(date_time + Duration::hours(4)),
            RollingWindow::Hours6 => Some(date_time + Duration::hours(6)),
            RollingWindow::Hours8 => Some(date_time + Duration::hours(8)),
            RollingWindow::Hours12 => Some(date_time + Duration::hours(12)),
            RollingWindow::Hours24 => Some(date_time + Duration::hours(24)),
            RollingWindow::Days1 => Some(date_time + Duration::days(1)),
            RollingWindow::Days2 => Some(date_time + Duration::days(2)),
            RollingWindow::Days3 => Some(date_time + Duration::days(3)),
            RollingWindow::Days7 => Some(date_time + Duration::days(7)),
            RollingWindow::Days14 => Some(date_time + Duration::days(14)),
            RollingWindow::Days30 => Some(date_time + Duration::days(30)),
            RollingWindow::Days45 => Some(date_time + Duration::days(45)),
            RollingWindow::Days60 => Some(date_time + Duration::days(60)),
            RollingWindow::Days90 => Some(date_time + Duration::days(90)),
            RollingWindow::Days180 => Some(date_time + Duration::days(180)),
            RollingWindow::Days360 => Some(date_time + Duration::days(360)),
            RollingWindow::Weeks1 => Some(date_time + Duration::weeks(1)),
            RollingWindow::Weeks2 => Some(date_time + Duration::weeks(2)),
            RollingWindow::Weeks4 => Some(date_time + Duration::weeks(4)),
            RollingWindow::Weeks10 => Some(date_time + Duration::weeks(10)),
            RollingWindow::Weeks20 => Some(date_time + Duration::weeks(20)),
            RollingWindow::Weeks40 => Some(date_time + Duration::weeks(40)),
        }
    }
}
